### PR TITLE
Rec base

### PR DESCRIPTION
**Pull request by tgsmith61591**
This branch adds the following new modules/scripts:
  - `install.sh`
    - A top-level script to install the entire package, assign global vars, etc. Several to-dos remain in this file, but should be handled in another feature branch.
  - `metrics` module for pairwise vector similarity computations
  - `recommend` module for recommender implementations. The base class has been built-in, but full algos will be implemented in future feature branches.
  - `utils.launch` module provides a function for launching pyspark within a python shell or script. It is used with the new `testing._testing.with_pyspark_connection` decorator for testing functions that require a pyspark connection.
  - The `utils.spark_validation` module provides two handy new functions: `check_X` and `check_X_y` for validating `RDD`s and `DataFrames` before use with algorithms.

The following amendments were made to existing modules:
  - `.travis.yml` now explicitly assembles the Gradle components
  - `build.gradle` now installs Scala, adds the scala plugin, and installs Spark 1.6.3.

Though several components (primarily the `recommend` module) are incomplete, enough high-importance additions were part of this feature, that I felt it important to merge into `develop` before continuing with further feature branches that might diverge and create painful merge conflicts.

### CODE REVIEW

**Comment by tgsmith61591** [comment]
This drops some coverage (not on pre-existing modules; only on new ones), but once merged and branched into other features, we can go down the Sisyphean path of painstakingly testing everything :octocat:

**Comment by tgsmith61591** [comment]
Merging the `rec-base-testing` branch in resolves a lot of the issues we were seeing, and provides the functionality to test with PySpark connections. See the `alkaline.utils.PySparkContext` (in the `launch.py` file) singleton class, which prevents repeated teardown and setup of SparkContexts for testing.

Though this branch doesn't complete the initial recommenders, it does add significant core functionality and should be merged now for other feature branches to be able to use its additions.

**Comment by tgsmith61591** [comment]
The drop in coverage is actually because it was counting coverage over the actual `pyspark` python package too. I specified `--cover-package=alkaline` and hoping that will fix it.

**Comment by tgsmith61591** [comment]
OK, ready for review.

**Comment by charlesdrotar** [comment]
Ran tests. LGTM!

**Pull request merged**
