### PR TITLE
initial commit of sphinx documentation and clean up some docstrings

### PR DESCRIPTION
**Pull request by charlesdrotar**
- Uses the napolean sphinx extension that automatically parses either google or numpy docstrings.
  - In the past we had relied on the ``sphinxext/numpy/`` folder 
  - [napolean within conf.py](https://github.com/charlesdrotar/alkaline/blob/gh-pages-documentation/docs/conf.py#L35-L57)
- We are going to rely on Github's automatic building of gh-pages via commits to docs folder in master instead of manually building the gh-pages branch.

There are some lingering ``.. todos :: `` within the .rst files that need to get resolved prior to getting put into master (examples, logo, and testing setup). For now the basis of the documentation is wired up though. 

**Run this to build the documentation for review:**
```bash
sphinx-build -b html . [path to base dir of repo]/build
```

### CODE REVIEW

**Comment by tgsmith61591** [comment]
Nice one! Want me to draft up a logo later?

**Comment by charlesdrotar** [comment]
If you would like to do the logo that would be fantastic :)!

**Comment by charlesdrotar** [comment]
This PR will address [issue#6](https://github.com/charlesdrotar/alkaline/issues/6) and [issue#8](https://github.com/charlesdrotar/alkaline/issues/8).

**Comment by tgsmith61591** [comment]
All checks passing, merging into develop right now. Next step is to address logo req and some todos in #6

**Pull request merged**
